linters:
  enable:
    - gofmt
    - golint
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - misspell
    - unconvert
    - gosec
    - prealloc
    - unused
    - goconst
    - gocyclo
    - dupl
    - gocritic
    - gochecknoinits
    - gochecknoglobals

run:
  deadline: 5m
  tests: true
  skip-dirs:
    - vendor
    - docs

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - dupl
        - gocyclo

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true 